; Elemental types
NORMAL   EQU $00
FIGHTING EQU $01
FLYING   EQU $02
POISON   EQU $03
GROUND   EQU $04
ROCK     EQU $05
BUG      EQU $06
GHOST    EQU $07
STEEL    EQU $08
FIRE     EQU $09
WATER    EQU $0A
GRASS    EQU $0B
ELECTRIC EQU $0C
PSYCHIC  EQU $0D
ICE      EQU $0E
DRAGON   EQU $0F
DARK     EQU $10
FAIRY    EQU $11
CRYSTAL  EQU $12 ; CRYSTAL ONIX ONLY
TYPE_UNK EQU $13 ; Typeless (Struggle)

; These are for the Physical Special split
PHYSICAL  EQU $00
SPECIAL   EQU $01
STATUS_M  EQU $02
