ItemNames:
	db "POKé BALL@"
	db "GREAT BALL@"
	db "ULTRA BALL@"
	db "MASTER BALL@"
	db "SAFARI BALL@"
	db "FAST BALL@"
	db "LEVEL BALL@"
	db "LURE BALL@"

	db "HEAVY BALL@"
	db "LOVE BALL@"
	db "FRIEND BALL@"
	db "MOON BALL@"
	db "SNAG BALL@"
	db "POTION@"
	db "SUPER POTION@"
	db "HYPER POTION@"

	db "MAX POTION@"
	db "ANTIDOTE@"
	db "BURN HEAL@"
	db "ICE HEAL@"
	db "AWAKENING@"
	db "PARLYZ HEAL@"
	db "FULL HEAL@"
	db "FULL RESTORE@"

	db "REVIVE@"
	db "MAX REVIVE@"
	db "FRESH WATER@"
	db "SODA POP@"
	db "LEMONADE@"
	db "MOO MOO MILK@"
	db "ETHER@"
	db "MAX ETHER@"

	db "ELIXER@"
	db "MAX ELIXER@"
	db "HP UP@"
	db "PROTEIN@"
	db "IRON@"
	db "CARBOS@"
	db "CALCIUM@"
	db "ZINC@"

	db "PP UP@"
	db "PP MAX@"
	db "RARE CANDY@"
	db "X ATTACK@"
	db "X DEFEND@"
	db "X SPEED@"
	db "X SP. ATK@"
	db "X SP. DEF@"

	db "X ACCURACY@"
	db "DIRE HIT@"
	db "GUARD SPEC.@"
	db "REPEL@"
	db "SUPER REPEL@"
	db "MAX REPEL@"
	db "LURE@"
	db "SUPER LURE@"

	db "MAX LURE@"
	db "ESCAPE ROPE@"
	db "POKé DOLL@"
	db "FIRE STONE@"
	db "THUNDERSTONE@"
	db "WATER STONE@"
	db "LEAF STONE@"
	db "ICE STONE@"

	db "SUN STONE@"
	db "MOON STONE@"
	db "KING'S ROCK@"
	db "METAL COAT@"
	db "DRAGON SCALE@"
	db "UPGRADE@"
	db "DUBIOUS DISC@"
	db "DOME FOSSIL@"

	db "HELIX FOSSIL@"
	db "OLD AMBER@"
	db "PEARL@"
	db "BIG PEARL@"
	db "STAR PIECE@"
	db "STARDUST@"
	db "NUGGET@"
	db "BIG NUGGET@"

	db "OAK's PARCEL@"
	db "TOWN MAP@"
	db "TM CASE@"
	db "POKéMON BOX@"
	db "ITEMFINDER@"
	db "EXP. SHARE@"
	db "S.S. TICKET@"
	db "OLD ROD@"
	db "GOOD ROD@"
	db "SUPER ROD@"
	db "VS. SEEKER@"
	db "BIKE VOUCHER@"
	db "BICYCLE@"
	db "COIN CASE@"
	db "LIFT KEY@"
	db "CARD KEY@"
	db "SILPH SCOPE@"
	db "POKé FLUTE@"
	db "GOLD TEETH@"
	db "SECRET KEY@"
	db "SHINY CHARM@"
	db "OLD SEA MAP@"
	db "MEGA STONE X@"
	db "MEGA STONE Y@"
	db "MELTAN BOX@"

	db "POKEDEX@"
	db "SURFBOARD@"
	db "BAIT@"
	db "ROCK@"

; Only used in menus, not normal items
	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"
	db "B4F@"
